import { Clinic } from "./types";

export const MOCK_CLINICS: Clinic[] = [
  {
    id: "1",
    name: "Muscatine Community Health Center",
    address: "1518 Mulberry Ave, Muscatine, IA 52761",
    phone: "(563) 264-9100",
    distance: "1.4 mi",
    open: true,
    type: "family",
    insurance: ["Medicaid", "Medicare", "Uninsured OK", "BCBS", "Aetna"],
    services: ["Primary Care", "Lab Tests", "Immunizations", "Pediatrics"],
    telehealth: true,
    sliding: true,
    lat: 41.4245,
    lng: -91.0432,
  },
  {
    id: "2",
    name: "FQHC Sliding Scale Clinic",
    address: "423 Iowa Ave, Muscatine, IA 52761",
    phone: "(563) 263-4100",
    distance: "2.1 mi",
    open: true,
    type: "uninsured",
    insurance: ["Uninsured OK", "Medicaid", "Sliding Scale"],
    services: ["Primary Care", "Women's Health", "Dental", "Behavioral Health"],
    telehealth: false,
    sliding: true,
    lat: 41.4198,
    lng: -91.0478,
  },
  {
    id: "3",
    name: "Muscatine Vet Center",
    address: "211 E 2nd St, Muscatine, IA 52761",
    phone: "(563) 607-0836",
    distance: "1.8 mi",
    open: true,
    type: "veteran",
    insurance: ["VA Eligible", "VA Benefits"],
    services: ["PTSD Counseling", "MST Support", "Family Therapy", "Benefits Help"],
    telehealth: true,
    sliding: false,
    lat: 41.4231,
    lng: -91.0445,
  },
  {
    id: "4",
    name: "River Valley Mental Health",
    address: "1206 Cedar St, Muscatine, IA 52761",
    phone: "(563) 264-9200",
    distance: "3.0 mi",
    open: false,
    type: "mental",
    insurance: ["Medicaid", "Medicare", "BCBS", "Aetna", "Uninsured OK"],
    services: ["Depression", "Anxiety", "PTSD", "Addiction", "Crisis Support"],
    telehealth: true,
    sliding: true,
    lat: 41.4156,
    lng: -91.0512,
  },
  {
    id: "5",
    name: "Genesis Medical Center ER",
    address: "1227 E Rusholme St, Davenport, IA 52803",
    phone: "(563) 421-1000",
    distance: "4.2 mi",
    open: true,
    type: "er",
    insurance: ["All Insurance", "Uninsured OK", "Medicaid", "Medicare"],
    services: ["Emergency Care", "Trauma", "Surgery", "Imaging"],
    telehealth: false,
    sliding: false,
    lat: 41.5236,
    lng: -90.5776,
  },
  {
    id: "6",
    name: "Iowa City VA Medical Center",
    address: "601 Highway 6 W, Iowa City, IA 52246",
    phone: "(319) 338-0581",
    distance: "28 mi",
    open: true,
    type: "veteran",
    insurance: ["VA Eligible", "VA Benefits", "Medicare"],
    services: ["Primary Care", "Mental Health", "Surgery", "Pharmacy", "Specialty Care"],
    telehealth: true,
    sliding: false,
    lat: 41.6611,
    lng: -91.5302,
  },
  {
  id: "7",
  name: "Muscatine Family Dental",
  address: "1920 Cedar St, Muscatine, IA 52761",
  phone: "(563) 263-5555",
  distance: "1.2 mi",
  open: true,
  type: "dental",
  insurance: ["Medicaid", "Medicare", "BCBS", "Uninsured OK"],
  services: ["General Dentistry", "Emergency Dental", "Cleanings", "X-Rays"],
  telehealth: false,
  sliding: true,
  lat: 41.4198,
  lng: -91.0512,
},
];